name: Test jobs functions

on:
  push
  
jobs:
  create-file:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.step1.outputs.LINE }}
    steps:
      - name: generate file
        id: step1
        env:
          MYVAR: quan 
        run: |
          touch printfile
          echo "LINE=My name is $MYVAR." >> $GITHUB_OUTPUT
  
  print:
    runs-on: ubuntu-latest
    needs: create-file
    steps:
      - name: print content of printfile
        run: |
          echo ${{needs.create-file.outputs.content}}
